language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - python --version
  - pip install -U flake8
  - pip install -U ansible
  - pip install -U codecov
  - pip install -U molecule docker
  - pip install pytest==5.3.4
  - ansible --version
  - molecule --version
  - pytest --version
script:
  - ./travis_run.sh
after_success:
  - codecov # submit coverage
