---
# tasks file for cassandra_linux
- name: Include vars for OS family
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['os_family'] }}.yml"

- name: Check is_docker.txt file exists
  ansible.builtin.stat:
    path: is_docker.txt
  register: is_docker

- name: Disable Swap
  ansible.builtin.command: swapoff -a
  when:
    - is_docker.stat.exists == False
    - ansible_swaptotal_mb > 0

- name: Remove swap partitions
  ansible.builtin.mount:
    path: swap
    state: absent

- name: Ensure Swappiness is 1
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "1"
    sysctl_set: yes
    reload: yes

- name: Ensure max_map_count is 1048575
  ansible.builtin.sysctl:
    name: vm.max_map_count
    value: "1048575"
    sysctl_set: yes
    reload: yes

- name: Install time sync package
  ansible.builtin.package:
    name: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('systemd-timesyncd', 'chrony') }}"
    state: present
  retries: 3

- name: Ensure ntp service starts
  ansible.builtin.service:
    name: "{{ ntp_service }}"
    enabled: yes
    state: started

- name: Ensure limits are set
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    block: |
      cassandra - memlock unlimited
      cassandra - nofile 100000
      cassandra - nproc 32768
      cassandra - as unlimited
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    state: present

- name: Extra Limit for RH Derived Distros
  ansible.builtin.lineinfile:
    path: /etc/security/limits.d/90-nproc.conf
    regexp: "^\\* - nproc 32768"
    line: "* - nproc 32768"
    create: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: TCP setting for prevents timeouts and handling many connections
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  with_items:
    - { key: net.ipv4.tcp_keepalive_time, value: 60 }
    - { key: net.ipv4.tcp_keepalive_probes, value: 3 }
    - { key: net.ipv4.tcp_keepalive_intvl, value: 10 }
    - { key: net.core.rmem_max, value: 16777216 }
    - { key: net.core.wmem_max, value: 16777216 }
    - { key: net.core.rmem_default, value: 16777216 }
    - { key: net.core.wmem_default, value: 16777216 }
    - { key: net.core.optmem_max, value: 40960 }
    - { key: net.ipv4.tcp_rmem, value: "4096 87380 16777216" }
    - { key: net.ipv4.tcp_wmem, value: "4096 65536 16777216" }
  when:
    - is_docker.stat.exists == False

- name: Disable zone_reclaim_mode
  ansible.builtin.sysctl:
    name: vm.zone_reclaim_mode
    value: 0
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  when:
    - is_docker.stat.exists == False

- name: Ensure disable-thp service file exists
  ansible.builtin.copy:
    src: disable-thp.service
    dest: /etc/systemd/system/
  register: thp

- name: Ensure service to disable THP exists
  ansible.builtin.systemd:
    name: disable-thp
    daemon-reload: yes
    state: started
    enabled: yes
  when: thp.changed == True
