---
driver:
  name: docker
platforms:
  - name: amazon2023
    image: geerlingguy/docker-amazonlinux2023-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    user: root
  - name: ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    user: root
  - name: almalinux9
    image: mullholland/docker-almalinux-systemd:9
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    user: root
  - name: rockylinux9
    image: geerlingguy/docker-rockylinux9-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    user: root
provisioner:
  name: ansible
verifier:
  name: testinfra
