---
- name: Prepare
  hosts: all

  tasks:

  - name: Install epel for RedHat based systems
    yum:
      name: epel-release
    register: epel
    when: ansible_os_family == "RedHat"

  - name: Run yum clean all
    shell: yum clean all
    args:
      command_warnings: False
    when:
      - ansible_os_family == "RedHat"
      - epel.changed == True

  - name: Install debian packages (Debian & Ubuntu)
    apt:
     name: ["apt-transport-https", "curl", "gnupg"]
     state: present
    when: ansible_os_family == "Debian"

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == "Debian"

 #- name: Enable universe repository for Ubuntu systems
  #  apt_repository:
  #    repo: "{{ item }}"
  #  loop:
  #    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
  #    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
  #    - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
